Error output test
2024-05-06 14:19:06.438368: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2024-05-06 14:19:06.581129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:21:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.34GiB deviceMemoryBandwidth: 648.29GiB/s
2024-05-06 14:19:06.586574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2024-05-06 14:19:06.644075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2024-05-06 14:19:06.678513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2024-05-06 14:19:06.687914: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2024-05-06 14:19:06.747830: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2024-05-06 14:19:06.758078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2024-05-06 14:19:06.861672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2024-05-06 14:19:06.868539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2024-05-06 14:19:08.751491: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2024-05-06 14:19:08.782961: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1996205000 Hz
2024-05-06 14:19:08.783590: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f163c000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-05-06 14:19:08.783614: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-05-06 14:19:08.910985: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x9520c70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-05-06 14:19:08.911020: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA A40, Compute Capability 8.6
2024-05-06 14:19:08.913614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:21:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.34GiB deviceMemoryBandwidth: 648.29GiB/s
2024-05-06 14:19:08.913658: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2024-05-06 14:19:08.913667: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2024-05-06 14:19:08.913675: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2024-05-06 14:19:08.913682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2024-05-06 14:19:08.913689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2024-05-06 14:19:08.913696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2024-05-06 14:19:08.913704: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2024-05-06 14:19:08.916203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2024-05-06 14:19:08.916604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2024-05-06 14:19:08.918299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-06 14:19:08.918315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2024-05-06 14:19:08.918319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2024-05-06 14:19:08.921387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 42414 MB memory) -> physical GPU (device: 0, name: NVIDIA A40, pci bus id: 0000:21:00.0, compute capability: 8.6)
2024-05-06 14:19:14.429404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2024-05-06 14:23:08.789726: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/users/mdoan4/.local/lib/python3.8/site-packages/nibabel/loadsave.py", line 100, in load
    stat_result = os.stat(filename)
OSError: [Errno 5] Input/output error: '/data/users1/mdoan4/babywire/babytrainingdata/labeling2_inf10_final4.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 110, in <module>
    wirehead_runtime.run_generator()
  File "/data/users1/mdoan4/wirehead/wirehead/Runtime.py", line 225, in run_generator
    self.generate_and_insert(dbw, dbc, chunksize)
  File "/data/users1/mdoan4/wirehead/wirehead/Runtime.py", line 202, in generate_and_insert
    data = next(self.generator)
  File "worker.py", line 53, in create_generator
    img, lab = preprocessing_pipe(brain_generator.generate_brain())
  File "/data/users1/mdoan4/wirehead/dependencies/synthseg/SynthSeg/brain_generator.py", line 324, in generate_brain
    (image, labels) = next(self.brain_generator)
  File "/data/users1/mdoan4/wirehead/dependencies/synthseg/SynthSeg/brain_generator.py", line 319, in _build_brain_generator
    model_inputs = next(self.model_inputs_generator)
  File "/data/users1/mdoan4/wirehead/dependencies/synthseg/SynthSeg/model_inputs.py", line 102, in build_model_inputs
    lab = utils.load_volume(path_label_maps[idx], dtype='int', aff_ref=np.eye(4))
  File "/data/users1/mdoan4/wirehead/dependencies/synthseg/ext/lab2im/utils.py", line 92, in load_volume
    x = nib.load(path_volume)
  File "/home/users/mdoan4/.local/lib/python3.8/site-packages/nibabel/loadsave.py", line 102, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/data/users1/mdoan4/babywire/babytrainingdata/labeling2_inf10_final4.nii.gz'
